chore: check deps scripts

diff --git a/check_linux_deps b/check_linux_deps
--- a/check_linux_deps
+++ b/check_linux_deps
@@ -2,7 +2,22 @@
 
 set -e
 
-if ! type fish &> /dev/null; then
-  echo "please install fish"
-  exit 1
-fi
+declare -a required_tools=("git" "curl" "apt")
+
+for tool in "${required_tools[@]}"; do
+  if ! type "$tool" &> /dev/null; then
+    echo "FAIL: Please install \`$tool\`"
+    exit 1
+  fi
+done
+
+
+# TODO: figure out later...
+declare -a required_deps=("asdf" "fish" "nvim" "node" "python3" "ruby")
+
+for dep in "${required_deps[@]}"; do
+  if ! type "$dep" &> /dev/null; then
+    echo "FAIL: Please \`sudo apt install $dep\`"
+    exit 1
+  fi
+done
diff --git a/check_macos_deps b/check_macos_deps
--- a/check_macos_deps
+++ b/check_macos_deps
@@ -2,10 +2,21 @@
 
 set -e
 
-if ! type fish &> /dev/null; then
-  echo "please install fish"
-  exit 1
-else
-  echo "fish is installed"
-  echo "continuing..."
-fi
+declare -a required_tools=("git" "curl" "brew")
+
+for tool in "${required_tools[@]}"; do
+  if ! type "$tool" &> /dev/null; then
+    echo "FAIL: Please install \`$tool\`"
+    exit 1
+  fi
+done
+
+
+declare -a required_deps=("asdf" "fish" "nvim" "node" "python3" "ruby")
+
+for deps in "${required_deps[@]}"; do
+  if ! type "$deps" &> /dev/null; then
+    echo "FAIL: Please \`brew install $deps\`"
+    exit 1
+  fi
+done
